### ISSUE TITLE
KafkaMessageSender doesn't send messages

### ISSUE THREAD

**Issue by maxsel** [tudorzgureanu/scala-kafka-protobuf#1]
Hey @tudorzgureanu,

I'm trying to run your example. I do first two steps (docker-compose and runMain com.tudorzgureanu.Main) and everything works fine, but when I run _sbt "runMain com.tudorzgureanu.KafkaMessageSender"_, no printlns appear in terminal, so I assume Futures don't complete. Extending Thread.sleep() value doesn't help.

Could you please elaborate on that?

Thanks in advance!

**Comment by dimowski** [comment]
@tudorzgureanu setting all log levels in `logback.xml` to `DEBUG` helped us to reveal exceptions in logs: 
> java.io.IOException: Can’t resolve address: kafka:29092

So changing _**KAFKA_ADVERTISED_LISTENERS**_ value in `docker-compose.yml` from `PLAINTEXT://kafka:29092` to `PLAINTEXT://localhost:29092` resolved the issue.
Please review PR https://github.com/tudorzgureanu/scala-kafka-protobuf/pull/2.

**Comment by tudorzgureanu** [comment]
Looks like I had kafka in my hosts file for convenience for a long while. 😂 

Thanks @maxsel and @dmkach for raising and fixing this issue. 👍
